### ISSUE TITLE
Mixes up the building categories

### ISSUE THREAD

**Issue by RickardZwahlen** [AlexanderDzhoganov/Skylines-ImprovedBuildPanel#1]
When the mod is enabled the buttons to change between building categories (like buses, trains, boats etc) don't open the correct category. For example, clicking the bus tab might open the train tab one time and the boat tab the next.

**Comment by AlexanderDzhoganov** [comment]
This mod is now obsolete. Consider trying out [Sapphire](http://steamcommunity.com/sharedfiles/filedetails/?id=421770876) and wait until nice skins for it are developed :)
